---
# file: tasks/use-yum.yml
#
# Configure td-agent from YUM repository.
#

- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present

- name: amz-linux 2018.03
  include: use-yum-amz-linux-2018.03.yml
  when: ansible_distribution_version == '2018.03'

- name: all other amz-linux/redhat
  include: use-yum-common.yml
  when: ansible_distribution_version != '2018.03'
